#
# Copyright (C) 2020-2024 Lin Song <linsongui@gmail.com>
#
# This work is licensed under the Creative Commons Attribution-ShareAlike 3.0
# Unported License: http://creativecommons.org/licenses/by-sa/3.0/
#
# Attribution required: please include my name in any derivative and let me
# know how you have improved it!

name: build cron

on:
  schedule:
    - cron: '25 2 * * 0,4'

jobs:
  check_urls:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/check_urls.yml

  test_set_1:
    needs: check_urls
    uses: ./.github/workflows/test_set_1.yml

  test_set_2:
    needs: check_urls
    uses: ./.github/workflows/test_set_2.yml
