#
# Copyright (C) 2020-2022 Lin Song <linsongui@gmail.com>
#
# This work is licensed under the Creative Commons Attribution-ShareAlike 3.0
# Unported License: http://creativecommons.org/licenses/by-sa/3.0/
#
# Attribution required: please include my name in any derivative and let me
# know how you have improved it!

name: build

on:
  push:
    branches: [master]
    paths:
      - '**.sh'
      - '.github/workflows/main.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/check_urls.yml'
      - '.github/workflows/test_set_1.yml'
      - '.github/workflows/test_set_2.yml'

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  check_urls:
    needs: shellcheck
    uses: ./.github/workflows/check_urls.yml

  test_set_1:
    needs: [shellcheck, check_urls]
    uses: ./.github/workflows/test_set_1.yml

  test_set_2:
    needs: [shellcheck, check_urls]
    uses: ./.github/workflows/test_set_2.yml
